
spring.datasource.url=jdbc:mysql://localhost:3306/perfumeshop1
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=${PORT:8080}
server.address=0.0.0.0


payos.client-id=a74d29d7-c2d7-4ec0-b138-64fe52fd6e74
payos.api-key=947c8b32-6625-4385-a4c8-234e35e9656a
payos.checksum-key=4e32e1576a3eacf3d564a0151fbacece8c3225bef1f9e254e505bccaac307f59


payos.return-url=https://pendant-moustache-flask.ngrok-free.dev/thanh-toan/ket-qua
payos.cancel-url=https://pendant-moustache-flask.ngrok-free.dev/thanh-toan/ket-qua


# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuyen88931600@gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# JWT Configuration
app.jwt.secret=perfumeshop-luan-van-tot-nghiep-secret-key-2024-must-be-256-bits-long!!
app.jwt.expiration-ms=86400000
